insert into items ( title, price) values  ('Flower - Dish Garden', 183);
insert into items ( title, price) values  ('Corn - On The Cob', 88);
insert into items ( title, price) values  ('Figs', 64);
insert into items ( title, price) values  ('Wine - Alsace Gewurztraminer', 91);
insert into items ( title, price) values  ('Versatainer Nc - 8288', 112);
insert into items ( title, price) values  ('Chicken - Tenderloin', 137);
insert into items ( title, price) values  ('Lamb - Leg, Diced', 141);
insert into items ( title, price) values  ('Salt And Pepper Mix - Black', 60);
insert into items ( title, price) values  ('Corn - Cream, Canned', 122);
insert into items ( title, price) values ( 'Vaccum Bag - 14x20', 61);
insert into items ( title, price) values ( 'Dried Cherries', 44);
insert into items ( title, price) values ( 'Veal - Sweetbread', 121);
insert into items ( title, price) values ( 'Baking Powder', 118);
insert into items ( title, price) values ( 'Muffin - Blueberry IndivDEFAULTual', 119);
insert into items ( title, price) values ( 'Soup Campbells - Tomato Bisque', 166);
insert into items ( title, price) values ( 'Lettuce - Lambs Mash', 136);
insert into items ( title, price) values ( 'Wine - Masi Valpolocell', 168);
insert into items ( title, price) values ( 'Wine - White, Pinot Grigio', 38);
insert into items ( title, price) values ( 'Water - Spring Water, 355 Ml', 68);
insert into items ( title, price) values ( 'Beef - Diced', 172);
insert into items ( title, price) values ( 'Blue Curacao - Marie Brizard', 222);
insert into items ( title, price) values ( 'Oil - Truffle, White', 109);
insert into items ( title, price) values ( 'Tomato - Peeled Italian Canned', 225);
insert into items ( title, price) values ( 'Calypso - Lemonade', 78);
insert into items ( title, price) values ( 'Tomatoes Tear Drop Yellow', 58);
insert into items ( title, price) values ( 'Wine - White, Mosel Gold', 135);
insert into items ( title, price) values ( 'Cream - 10%', 227);
insert into items ( title, price) values ( 'Coconut Milk - Unsweetened', 60);
insert into items ( title, price) values ( 'Shichimi Togarashi Peppeers', 207);
insert into items ( title, price) values ( 'Heavy Duty Dust Pan', 149);
insert into items ( title, price) values ( 'Eggplant Italian', 90);
insert into items ( title, price) values ( 'Doilies - 5, Paper', 188);
insert into items ( title, price) values ( 'Tortillas - Flour, 12', 158);
insert into items ( title, price) values ( 'Curry Paste - Madras', 93);
insert into items ( title, price) values ( 'Versatainer Nc - 888', 138);
insert into items ( title, price) values ( 'Clams - Canned', 94);
insert into items ( title, price) values ( 'Cookies Cereal Nut', 185);
insert into items ( title, price) values ( 'Milk - Chocolate 250 Ml', 111);
insert into items ( title, price) values ( 'Juice Peach Nectar', 54);
insert into items ( title, price) values ( 'Pork - Loin, Center Cut', 70);
insert into items ( title, price) values ( 'Salad Dressing', 207);
insert into items ( title, price) values ( 'Shrimp - 100 / 200 Cold Water', 187);
insert into items ( title, price) values ( 'Grapefruit - Pink', 163);
insert into items ( title, price) values ( 'Coffee Cup 8oz 5338cd', 147);
insert into items ( title, price) values ( 'Sausage - Breakfast', 61);
insert into items ( title, price) values ( 'Wooden Mop Handle', 227);
insert into items ( title, price) values ( 'Muffin Mix - Chocolate Chip', 40);
insert into items ( title, price) values ( 'Fish - Artic Char, Cold Smoked', 24);
insert into items ( title, price) values ( 'Southern Comfort', 205);
insert into items ( title, price) values ( 'Bread - White Mini Epi', 181);
insert into items ( title, price) values ( 'Table Cloth 72x144 White', 206);
insert into items ( title, price) values ( 'Food Colouring - Blue', 30);
insert into items ( title, price) values ( 'Yucca', 14);
insert into items ( title, price) values ( 'Canadian Emmenthal', 195);
insert into items ( title, price) values ( 'Cranberries - Frozen', 182);
insert into items ( title, price) values ( 'Wine - German Riesling', 221);
insert into items ( title, price) values ( 'Tea - Herbal - 6 Asst', 99);
insert into items ( title, price) values ( 'Fruit Mix - Light', 111);
insert into items ( title, price) values ( 'Butcher Twine 4r', 142);
insert into items ( title, price) values ( 'Waffle Stix', 81);
insert into items ( title, price) values ( 'Salt - Celery', 47);
insert into items ( title, price) values ( 'Garam Masala Powder', 133);
insert into items ( title, price) values ( 'Isomalt', 151);
insert into items ( title, price) values ( 'Graham Cracker Mix', 91);
insert into items ( title, price) values ( 'Tart - Pecan Butter Squares', 43);
insert into items ( title, price) values ( 'Wine - Alsace Riesling Reserve', 112);
insert into items ( title, price) values ( 'Beer - Paulaner Hefeweisse', 103);
insert into items ( title, price) values ( 'Chocolate - Dark', 34);
insert into items ( title, price) values ( 'Sparkling Wine - Rose, Freixenet', 197);
insert into items ( title, price) values ( 'Pepper - Gypsy Pepper', 14);
insert into items ( title, price) values ( 'Cheese - Bocconcini', 134);
insert into items ( title, price) values ( 'Dried Cranberries', 141);
insert into items ( title, price) values ( 'Lychee', 84);
insert into items ( title, price) values ( 'Corn Kernels - Frozen', 172);
insert into items ( title, price) values ( 'Lettuce - Boston Bib', 63);
insert into items ( title, price) values ( 'Otomegusa Dashi Konbu', 50);
insert into items ( title, price) values ( 'Juice - Orange 1.89l', 79);
insert into items ( title, price) values ( 'Tea - Green', 182);
insert into items ( title, price) values ( 'Wine - Cotes Du Rhone Parallele', 127);
insert into items ( title, price) values ( 'Bacardi Breezer - Strawberry', 162);
insert into items ( title, price) values ( 'Fish - Halibut, Cold Smoked', 136);
insert into items ( title, price) values ( 'Corn Syrup', 193);
insert into items ( title, price) values ( 'Mustard - Seed', 77);
insert into items ( title, price) values ( 'Bagelers - Cinn / Brown Sugar', 87);
insert into items ( title, price) values ( 'Energy Drink Red Bull', 217);
insert into items ( title, price) values ( 'Jameson - Irish Whiskey', 24);
insert into items ( title, price) values ( 'Sugar - Palm', 93);
insert into items ( title, price) values ( 'Peas - Frozen', 59);
insert into items ( title, price) values ( 'Table Cloth 62x114 White', 95);
insert into items ( title, price) values ( 'Lamb - Pieces, Diced', 212);
insert into items ( title, price) values ( 'Beef - Prime Rib Aaa', 72);
insert into items ( title, price) values ( 'LDEFAULT Tray - 16in Dome', 159);
insert into items ( title, price) values ('Wine - Red, Lurton Merlot De', 33);
insert into items ( title, price) values ( 'Plasticknivesblack', 111);
insert into items ( title, price) values ( 'Alize Sunset', 140);
insert into items ( title, price) values ( 'Fond - Neutral', 168);
insert into items ( title, price) values ( 'Icecream Bar - Del Monte', 107);
insert into items ( title, price) values ( 'Oil - Olive', 86);
insert into items ( title, price) values ( 'Beef - Ox Tongue', 200);
insert into items ( title, price) values ( 'Sole - Dover, Whole, Fresh', 184);